### ISSUE TITLE
How to prevent interpolation?

### ISSUE THREAD

**Issue by emre-sahinn** [Javier-Garzo/Marching-cubes-on-Unity-3D#13]
Hi @Javier-Garzo,
I am building a voxel game and I managed to make cubes but I couldn't find a way to prevent interpolation between ground and placed cube.
![image](https://user-images.githubusercontent.com/30238276/183929965-70d870de-06d8-45a8-9e7d-db140e284535.png)
I want to combine Minecraft-looking blocky voxels combined with a marching cube but this ugly-looking interpolation prevents me, how can I solve this?

**Comment by emre-sahinn** [comment]
![image](https://user-images.githubusercontent.com/30238276/183935431-360c36fc-5826-40e8-b5d5-ab460ecfe5c2.png)

**Comment by Javier-Garzo** [comment]
Achieve a result of a minecraft style need the correct use of interpolation for generate that type of cube style. 

The interpolation allow to hide that slope that you post in your images. Just check this image to get the idea:
![image](https://user-images.githubusercontent.com/58559223/184239087-c79a0ee7-5130-4ec2-a464-bf33d2f43d71.png)

Check the difference with no interpolation in the marching cubes.
Interpolation:
![image](https://user-images.githubusercontent.com/58559223/184239880-94272d05-6afa-4d08-a85f-a844514c54fc.png)

No interpolation:
![image](https://user-images.githubusercontent.com/58559223/184240043-9a2d88ab-df62-4c46-9fb2-dcdbe2552dd9.png)

You can see that the interpolation and the correct weight of the vertex is necessary to achieve the cube style.

I have been trying a write code for generate the correct type of terrain modification for this problem unsuccessfully.
I am researching for the problem/bug/bad implementation that now allow me to generate this type of terrain.

**Comment by emre-sahinn** [comment]
> Achieve a result of a minecraft style need the correct use of interpolation for generate that type of cube style.
> 
> The interpolation allow to hide that slope that you post in your images. Just check this image to get the idea: ![image](https://user-images.githubusercontent.com/58559223/184239087-c79a0ee7-5130-4ec2-a464-bf33d2f43d71.png)
> 
> Check the difference with no interpolation in the marching cubes. Interpolation: ![image](https://user-images.githubusercontent.com/58559223/184239880-94272d05-6afa-4d08-a85f-a844514c54fc.png)
> 
> No interpolation: ![image](https://user-images.githubusercontent.com/58559223/184240043-9a2d88ab-df62-4c46-9fb2-dcdbe2552dd9.png)
> 
> You can see that the interpolation and the correct weight of the vertex is necessary to achieve the cube style.
> 
> I have been trying a write code for generate the correct type of terrain modification for this problem unsuccessfully. I am researching for the problem/bug/bad implementation that now allow me to generate this type of terrain.

I think we need a custom triangulation table to prevent those slope areas, I don't need slopes I just need the flexibility of marching cubes but with a Minecraft look. Do you have any idea to remove all of the slopes? I just need sharp edges.

**Comment by Javier-Garzo** [comment]
But you want a cube terrain like minecraft, because if you want a minecraft looking game, you need a voxel terrain, that type of terrain have a flexibility similar to the marching cubes, so maybe it's a better solution.
