### ISSUE TITLE
Is the overhang right above slopes expected?

### ISSUE THREAD

**Issue by kinnexus** [Javier-Garzo/Marching-cubes-on-Unity-3D#14]
![image](https://user-images.githubusercontent.com/17818512/189384593-d9955ea8-8443-4db2-aef6-9f41082066c2.png)

I have really enjoyed looking through this project, but it seems that there is an overhang that appears immediately above slopes like the image above. These overhangs look a little strange, but they also interfere with a character attempting to walk up these slopes. Is that overhang intentional?

**Comment by Javier-Garzo** [comment]
It's not intentional, I try to solve several times and I can't achieve it. 
I think is a problem related with the noise and the terrain or maybe the interpolation.

**Comment by kinnexus** [comment]
Looking through the code this evening, I’m guessing that the problem is in this function

   public float3 interporlateVertex(float4 p1, float4 p2, out float interpolation)
    {
        interpolation = (isoLevel - p1.w) / (p2.w - p1.w);
        return math.lerp(new float3(p1.x,p1.y,p1.z), new float3(p2.x,p2.y,p2.z), interpolation);
    }

Specifically, I’m not sure that isoLevel is doing what you want it to, or perhaps you are sending in the wrong p1/p2 vertices. You are getting different vertex values for adjoining voxels that should have the same vertex value, which makes me think that the interpolation is giving a wrong outcome.

I’ll keep looking

**Comment by Javier-Garzo** [comment]
I investigate about the problem and its related to a mix of the way of calculating the  interpolation of the vertices, and the way to set the vertex weight of the surface of the terrain and the air ones.
I am looking for a solution.

**Comment by kinnexus** [comment]
Well, after a ton of debug I have a pretty good idea what your code does and while I’m not 100% happy with this solution, it’s much, much better than where it was last week.

In your biome terrain generators try setting the lastVertexWeigh without adjusting for isoLevel, like so

                           int lastVertexWeigh = (int)(255 * ( height % 1));//Weigh of the last vertex

This gets a reasonably smooth interpolation. I settled on this because the terrain adjustment routines hooked to the mouse buttons do the same thing; they use the entire byte range 0 to 255 rather than adjusting for isoLevel and they get nice, smooth interpolation.

**Comment by Javier-Garzo** [comment]
Sorry for no find a solution a try changing the interpolation algorithm from bilinial to lineal, and other solutions in the same part of the biomes (all code related with the lastVertexWeigh). And a busy month.

I see your solution as the current best , but it need to solve the problems with the paint of the terrain.

![image](https://user-images.githubusercontent.com/58559223/195315181-b2d989c4-73aa-491a-9bc6-d676d24e3803.png)

There is also a strange generation in the height differences
![image](https://user-images.githubusercontent.com/58559223/195315696-21b48ef3-c623-4ed7-bc55-4bebc574c684.png)

However , it's a more organic solution. Good job.
