### ISSUE TITLE
Alternative Biome Selection

### ISSUE THREAD

**Issue by coolcatcoder** [Javier-Garzo/Marching-cubes-on-Unity-3D#16]
Hey just an idea, but wouldn't it be better to pick a biome by generating 3 sets of float2 perlin or simplex noise, then you can treat those 3 noise values at every place as an rgb colour. Each biome can have a user set colour, whichever biome is closest to that colour at any given point is chosen as the biome. Due to it being perlin or simplex noise this gives quite satisfying biome blobs. But beware that some colours that the eye thinks look different, might actually be quite close in terms of distance! Hope ya have a great day!

**Comment by Javier-Garzo** [comment]
Sound like a good solution if you use the same textures for the ground in all biomes or same texture between that two biomes, then the color change is smoother and you don't get that border of texture between terrains. Then each biome can have his own noise height configuration with an extra color in the texture of ground mesh. I don't know if it is a lot of load for the GPU or memory, maybe with a shader.
