### ISSUE TITLE
Get Byte data from a vertex (placement objects)

### ISSUE THREAD

**Issue by PanchoL** [Javier-Garzo/Marching-cubes-on-Unity-3D#2]
### Hi, I am trying to implement a vegetation system (not seed yet), but I have not fully understood how the bytes work to obtain if a vertex is grass or snow for example.

The trees are placed on the ground not by biome, but by the type of vertex it is (material), but it does not work quite well

### Is there any way to get the byte of a certain vertex with raycast?

**This is an image of the progress:**
![Biome Vegetation](https://user-images.githubusercontent.com/36605619/104858961-8966ff00-5901-11eb-8483-787b7b44be2a.png)

**Comment by Javier-Garzo** [comment]
First of all, you have achieved very cool results.

For get the material of a vertex in a point you need two things: the chunk that contain it and the position (x,y,z) of the vertex in that chunk. When we have that two variables we can calculate the byte data position of the vertex, that have a size of 2 bytes one for save the weight of the chunk (how many material exist in that point) and the second the type of material. 


The explanation maybe is a little confused so i create the code for a better understanding, for get the material (byte) of a specific point in the world i created two new functions:

One for the class "Chunk":
Consist in get the second byte data (material) of a vertex (x,y,z) in a chunk.
```
    /// <summary>
    /// Get the material(byte) from a specific point in the chunk
    /// </summary>
    public byte GetMaterial(Vector3 vertexPoint)
    {
        int byteIndex = ((int)vertexPoint.x + (int)vertexPoint.z * Constants.CHUNK_VERTEX_SIZE + (int)vertexPoint.y * Constants.CHUNK_VERTEX_AREA) * Constants.CHUNK_POINT_BYTE;
        return data[byteIndex + 1];
    }
```

Other one for class "ChunkManager":
Consist in calculate the chunk that contains the point and what vertex is the next one, for call  the previous function.
```
    /// <summary>
    /// Get the material(byte) from a specific point in the world
    /// </summary>
    public byte GetMaterialFromPoint(Vector3 point)
    {
        point = new Vector3(point.x / Constants.VOXEL_SIDE, point.y / Constants.VOXEL_SIDE, point.z / Constants.VOXEL_SIDE);

        Vector3 vertexOrigin = new Vector3((int)point.x, (int)point.y, (int)point.z);

        //Chunk containing the point
        Vector2Int hitChunk = new Vector2Int(Mathf.CeilToInt((vertexOrigin.x + 1 - Constants.CHUNK_SIDE / 2) / Constants.CHUNK_SIDE),
                                        Mathf.CeilToInt((vertexOrigin.z + 1 - Constants.CHUNK_SIDE / 2) / Constants.CHUNK_SIDE));
        //VertexPoint of the point in the chunk (x,y,z)
        Vector3Int vertexChunk = new Vector3Int((int)(vertexOrigin.x - hitChunk.x * Constants.CHUNK_SIZE + Constants.CHUNK_VERTEX_SIZE / 2),
            (int)(vertexOrigin.y + Constants.CHUNK_VERTEX_HEIGHT / 2),
            (int)(vertexOrigin.z - hitChunk.y * Constants.CHUNK_SIZE + Constants.CHUNK_VERTEX_SIZE / 2));

        return chunkDict[hitChunk].GetMaterial(vertexChunk);
    }
```

if you want to use it only need a line of code:
`int mat = chunkManager.GetMaterialFromPoint(hit.point);`

The possible mat is related with the texture used, the default texture:
In this case the grass have the id '0' and the snow the id '3'.

![Terreno enumerado](https://user-images.githubusercontent.com/58559223/105044756-62c2d880-5a67-11eb-9f10-cd96530a56fc.png)

**Comment by PanchoL** [comment]
Thanks for the explanation, the solution is very similar to the one I got, but there is a bug that I do not understand why it happens, there are some points that do not give their corresponding material, for example there are some vertices that should be of type 0 ( grass) but it returns 9, and not only with grass, for some reason, is that what prevents me from continuing to implement the vegetation system.

what I do is make a condition that says something like if (GetMaterialFromPoint (hit.point) == (MaterialTree)) then the tree is placed, but they are not placed in all the positions that they should be, since there are vertices that it detects that they are 9 and the material 9 does not exist

**Comment by Javier-Garzo** [comment]
I replicate the bug, it is generated because the near vertex of the chunk to our point is a air vertex. The terrain generator assign the total number of material to the material of the air vertex  (because we don't have a specific material for the air, maybe a bad design decision, it's better reserve the id:0 for it). The code of the terrain generation for the air vertex:
```
else
{
	chunkData[index] = 0;
	chunkData[index + 1] = Constants.NUMBER_MATERIALS;
}
```

A possible solution is if we get the material from a air vertex (id: 9), we check the next vertex for looks a different material of the air. I update the "GetMaterialFromPoint" function for solve it:

```
    /// <summary>
    /// Get the material(byte) from a specific point in the world
    /// </summary>
    public byte GetMaterialFromPoint(Vector3 point)
    {
        point = new Vector3(point.x / Constants.VOXEL_SIDE, point.y / Constants.VOXEL_SIDE, point.z / Constants.VOXEL_SIDE);

        Vector3 vertexOrigin = new Vector3((int)point.x, (int)point.y, (int)point.z);

        //Chunk containing the point
        Vector2Int hitChunk = new Vector2Int(Mathf.CeilToInt((vertexOrigin.x + 1 - Constants.CHUNK_SIDE / 2) / Constants.CHUNK_SIDE),
                                        Mathf.CeilToInt((vertexOrigin.z + 1 - Constants.CHUNK_SIDE / 2) / Constants.CHUNK_SIDE));
        //VertexPoint of the point in the chunk (x,y,z)
        Vector3Int vertexChunk = new Vector3Int((int)(vertexOrigin.x - hitChunk.x * Constants.CHUNK_SIZE + Constants.CHUNK_VERTEX_SIZE / 2),
            (int)(vertexOrigin.y + Constants.CHUNK_VERTEX_HEIGHT / 2),
            (int)(vertexOrigin.z - hitChunk.y * Constants.CHUNK_SIZE + Constants.CHUNK_VERTEX_SIZE / 2));

        if (chunkDict[hitChunk].GetMaterial(vertexChunk) != Constants.NUMBER_MATERIALS)//not air material, we return it
        {
            return chunkDict[hitChunk].GetMaterial(vertexChunk);
        }
        else//Loop next vertex for get a other material different to air
        {
            //we check six next vertex 
            Vector3[] nextVertexPoints = new Vector3[6];
            nextVertexPoints[0] = new Vector3(vertexOrigin.x + 0, vertexOrigin.y - 1, vertexOrigin.z + 0);
            nextVertexPoints[1] = new Vector3(vertexOrigin.x + 1, vertexOrigin.y + 0, vertexOrigin.z + 0);
            nextVertexPoints[2] = new Vector3(vertexOrigin.x - 1, vertexOrigin.y + 0, vertexOrigin.z + 0);
            nextVertexPoints[3] = new Vector3(vertexOrigin.x + 0, vertexOrigin.y + 0, vertexOrigin.z + 1);
            nextVertexPoints[4] = new Vector3(vertexOrigin.x + 0, vertexOrigin.y + 0, vertexOrigin.z + 1);
            nextVertexPoints[5] = new Vector3(vertexOrigin.x + 0, vertexOrigin.y + 1, vertexOrigin.z + 0);
            List<byte> mats = new List<byte>();
            for (int i = 0; i < nextVertexPoints.Length; i++)
            {
                //Chunk of the vertexPoint
                hitChunk = new Vector2Int(Mathf.CeilToInt((nextVertexPoints[i].x + 1 - Constants.CHUNK_SIDE / 2) / Constants.CHUNK_SIDE),
                                                Mathf.CeilToInt((nextVertexPoints[i].z + 1 - Constants.CHUNK_SIDE / 2) / Constants.CHUNK_SIDE));
                //Position of the vertexPoint in the chunk (x,y,z)
                vertexChunk = new Vector3Int((int)(nextVertexPoints[i].x - hitChunk.x * Constants.CHUNK_SIZE + Constants.CHUNK_VERTEX_SIZE / 2),
                    (int)(nextVertexPoints[i].y + Constants.CHUNK_VERTEX_HEIGHT / 2),
                    (int)(nextVertexPoints[i].z - hitChunk.y * Constants.CHUNK_SIZE + Constants.CHUNK_VERTEX_SIZE / 2));

                if (chunkDict[hitChunk].GetMaterial(vertexChunk) != Constants.NUMBER_MATERIALS)//not air material, we return it
                {
                    return chunkDict[hitChunk].GetMaterial(vertexChunk);
                }
            }
        }

        return Constants.NUMBER_MATERIALS;//only air material in that point.
    }
```

Now you should avoid to get the id: 9, when you realize the raycast.

**Comment by PanchoL** [comment]
Wooooh!! it worked, the bug is fixed with that solution, Now I can continue with the vegetation system, thank you. I greatly appreciate your quick answer
