### ISSUE TITLE
Changing VOXEL_SIDE Error

### ISSUE THREAD

**Issue by Somshekardsi** [Javier-Garzo/Marching-cubes-on-Unity-3D#4]
I'm changing the voxel side to 0.5f and the result is, How to subdivide chunk to get more vertices?
![image](https://user-images.githubusercontent.com/66861200/120095943-5bfb4f00-c146-11eb-9e5c-d98560c96426.png)

**Comment by Javier-Garzo** [comment]
There was a problem with two constants in the chunk edit code that change the edit vertexs to wrong ones.
I upload a fix for it, changing the wrong constant for the correct ones. 
If you see other problems comment me here or confirm that all work as expected.

**Comment by Somshekardsi** [comment]
Thanks for the reply, issue got fixed.
