### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by GodOfMemes** [Javier-Garzo/Marching-cubes-on-Unity-3D#7]
I have two questions.

1. How and where can I add the code to smooth the terrain.
2. Does this support underground generation for example ores.

**Comment by Javier-Garzo** [comment]
1.For the first question with the current code (Marching Cubes algorithm) you always will get some voxel style, the "interpoalte" variable inside MeshBuilderManager gameobject can smooth the terrain a little but not create a full organic terrain. Tocreate a full organic terrain you can upgrade the Marching Cubes with [Dual Contouring](https://wordsandbuttons.online/interactive_explanation_of_marching_cubes_and_dual_contouring.html), in this serie of [videos](https://www.youtube.com/watch?v=PgZDp5Oih38&list=PLVsTSlfj0qsWt0qafrT6blp5yvchzO4ee&index=2) you can see that he upgrade the Marching Cubes with Dual Contouring and he obtain a organic terrain.

2.The terrain now only supports different layers of terrain that chage with the depth from suface. You can modify the current code to generate ores, but a better solution si to use a 3D noise to generate cave systems and ores.
